# Generated by Django 2.0.1 on 2018-01-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='game',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
