# Generated by Django 2.0.1 on 2018-01-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180126_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Game'),
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
