# Generated by Django 2.0.1 on 2018-01-27 12:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_mygames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygames',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL),
        ),
    ]
