# Generated by Django 2.0.1 on 2018-02-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.FileField(upload_to=''),
        ),
    ]
