# Generated by Django 2.0.1 on 2018-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180213_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='genere',
            field=models.CharField(max_length=10),
        ),
    ]
