# Generated by Django 2.0.1 on 2018-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180215_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylibrary',
            name='game',
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='games',
            field=models.ManyToManyField(to='assets.Game'),
        ),
    ]
