# Generated by Django 2.0.1 on 2018-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180226_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='games',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='assets.Game'),
        ),
    ]
