# Generated by Django 2.0.1 on 2018-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20180227_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='games',
            field=models.ManyToManyField(to='assets.Game'),
        ),
    ]
